default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: photos_organize_development


test:
  <<: *default
  database: photos_organize_test


production:
  <<: *default
  database: photos_organize_production
  username: photos_organize
  password: <%= ENV["PHOTOS_ORGANIZE_DATABASE_PASSWORD"] %>
